spring:
  datasource:
    url: jdbc:h2:mem:timesheetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/timesheet
    driverClassName: org.postgresql.Driver
    username: timesheet
    password: timesheet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

